#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="livegame")]
	public partial class DBCalendarioDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCalendario(Calendario instance);
    partial void UpdateCalendario(Calendario instance);
    partial void DeleteCalendario(Calendario instance);
    #endregion
		
		public DBCalendarioDataContext() : 
				base(global::Repositorio.Properties.Settings.Default.livegameConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBCalendarioDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBCalendarioDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBCalendarioDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBCalendarioDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Calendario> Calendarios
		{
			get
			{
				return this.GetTable<Calendario>();
			}
		}
		
		public System.Data.Linq.Table<Comentario> Comentarios
		{
			get
			{
				return this.GetTable<Comentario>();
			}
		}
		
		public System.Data.Linq.Table<Narracione> Narraciones
		{
			get
			{
				return this.GetTable<Narracione>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Calendario")]
	public partial class Calendario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _temporada;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private string _local;
		
		private string _visita;
		
		private System.Nullable<int> _pts_local;
		
		private System.Nullable<int> _pts_visita;
		
		private System.Nullable<int> _W;
		
		private System.Nullable<int> _L;
		
		private string _finalizado;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntemporadaChanging(string value);
    partial void OntemporadaChanged();
    partial void OnfechaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaChanged();
    partial void OnlocalChanging(string value);
    partial void OnlocalChanged();
    partial void OnvisitaChanging(string value);
    partial void OnvisitaChanged();
    partial void Onpts_localChanging(System.Nullable<int> value);
    partial void Onpts_localChanged();
    partial void Onpts_visitaChanging(System.Nullable<int> value);
    partial void Onpts_visitaChanged();
    partial void OnWChanging(System.Nullable<int> value);
    partial void OnWChanged();
    partial void OnLChanging(System.Nullable<int> value);
    partial void OnLChanged();
    partial void OnfinalizadoChanging(string value);
    partial void OnfinalizadoChanged();
    #endregion
		
		public Calendario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_temporada", DbType="VarChar(9)")]
		public string temporada
		{
			get
			{
				return this._temporada;
			}
			set
			{
				if ((this._temporada != value))
				{
					this.OntemporadaChanging(value);
					this.SendPropertyChanging();
					this._temporada = value;
					this.SendPropertyChanged("temporada");
					this.OntemporadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_local", DbType="VarChar(9)")]
		public string local
		{
			get
			{
				return this._local;
			}
			set
			{
				if ((this._local != value))
				{
					this.OnlocalChanging(value);
					this.SendPropertyChanging();
					this._local = value;
					this.SendPropertyChanged("local");
					this.OnlocalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visita", DbType="VarChar(9)")]
		public string visita
		{
			get
			{
				return this._visita;
			}
			set
			{
				if ((this._visita != value))
				{
					this.OnvisitaChanging(value);
					this.SendPropertyChanging();
					this._visita = value;
					this.SendPropertyChanged("visita");
					this.OnvisitaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pts_local", DbType="Int")]
		public System.Nullable<int> pts_local
		{
			get
			{
				return this._pts_local;
			}
			set
			{
				if ((this._pts_local != value))
				{
					this.Onpts_localChanging(value);
					this.SendPropertyChanging();
					this._pts_local = value;
					this.SendPropertyChanged("pts_local");
					this.Onpts_localChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pts_visita", DbType="Int")]
		public System.Nullable<int> pts_visita
		{
			get
			{
				return this._pts_visita;
			}
			set
			{
				if ((this._pts_visita != value))
				{
					this.Onpts_visitaChanging(value);
					this.SendPropertyChanging();
					this._pts_visita = value;
					this.SendPropertyChanged("pts_visita");
					this.Onpts_visitaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_W", DbType="Int")]
		public System.Nullable<int> W
		{
			get
			{
				return this._W;
			}
			set
			{
				if ((this._W != value))
				{
					this.OnWChanging(value);
					this.SendPropertyChanging();
					this._W = value;
					this.SendPropertyChanged("W");
					this.OnWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_L", DbType="Int")]
		public System.Nullable<int> L
		{
			get
			{
				return this._L;
			}
			set
			{
				if ((this._L != value))
				{
					this.OnLChanging(value);
					this.SendPropertyChanging();
					this._L = value;
					this.SendPropertyChanged("L");
					this.OnLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_finalizado", DbType="VarChar(5)")]
		public string finalizado
		{
			get
			{
				return this._finalizado;
			}
			set
			{
				if ((this._finalizado != value))
				{
					this.OnfinalizadoChanging(value);
					this.SendPropertyChanging();
					this._finalizado = value;
					this.SendPropertyChanged("finalizado");
					this.OnfinalizadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Comentarios")]
	public partial class Comentario
	{
		
		private System.Nullable<int> _id;
		
		private string _Nombre;
		
		private string _Cuerpo;
		
		private string _Twitter;
		
		public Comentario()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int")]
		public System.Nullable<int> id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(5)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cuerpo", DbType="VarChar(31)")]
		public string Cuerpo
		{
			get
			{
				return this._Cuerpo;
			}
			set
			{
				if ((this._Cuerpo != value))
				{
					this._Cuerpo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Twitter", DbType="VarChar(5)")]
		public string Twitter
		{
			get
			{
				return this._Twitter;
			}
			set
			{
				if ((this._Twitter != value))
				{
					this._Twitter = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Narraciones")]
	public partial class Narracione
	{
		
		private System.Nullable<int> _idJuego;
		
		private string _admin;
		
		private string _comment;
		
		private string _twitter;
		
		public Narracione()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idJuego", DbType="Int")]
		public System.Nullable<int> idJuego
		{
			get
			{
				return this._idJuego;
			}
			set
			{
				if ((this._idJuego != value))
				{
					this._idJuego = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin", DbType="VarChar(25)")]
		public string admin
		{
			get
			{
				return this._admin;
			}
			set
			{
				if ((this._admin != value))
				{
					this._admin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comment", DbType="VarChar(39)")]
		public string comment
		{
			get
			{
				return this._comment;
			}
			set
			{
				if ((this._comment != value))
				{
					this._comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_twitter", DbType="VarChar(6)")]
		public string twitter
		{
			get
			{
				return this._twitter;
			}
			set
			{
				if ((this._twitter != value))
				{
					this._twitter = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
